python里没有map方法，可以使用列表推导式

In [1]:
arr=[1,2,3]
double_arr=[x*2 for x in arr]
print(double_arr)

[2, 4, 6]


排序实例方法,变异方法，返回None

key 接受一个函数，用于指定排序的依据。

(method) def sort(
 *,
 key: None = None,
 reverse: bool = False
) -> None

Sort the list in ascending order and return None.

The sort is in-place (i.e. the list itself is modified) and stable (i.e. the order of two equal elements is maintained).

If a key function is given, apply it once to each list item and sort them, ascending or descending, according to their function values.

The reverse flag can be set to sort in descending order.


In [4]:
arr=[4,2,3,1]
# arr.sort() 等价于list.sort(key=None, reverse=False)
# arr.sort(key=None,reverse=True)
print(arr)

[4, 3, 2, 1]


创建数组
使用列表表达式或者numpy

In [7]:
a1=[1,2,3]
a2=[[1,2],[2,3]]
# 列表表达式
a3=[0 for _ in range(4)]
a4=[[0 for _ in range(4)] for _ in range(4)]
print(a1)
print(a2)
print(a3)
print(a4)

[1, 2, 3]
[[1, 2], [2, 3]]
[0, 0, 0, 0]
[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]


In [9]:
import numpy as np
print(np.full((3,4),1)) # zeros和ones是特殊情况
print(np.random.rand(3,4)) # 随机元素

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[0.13706094 0.41998882 0.76238419 0.91399037]
 [0.37546954 0.0012513  0.03718798 0.92882256]
 [0.11971173 0.31373175 0.36933496 0.27455565]]
